In [2]:
import torch

In [3]:
print(torch.__version__)

2.10.0


In [7]:
a.T

tensor([[-0.7753, -1.4649,  0.1951],
        [ 1.2343, -0.8087, -0.8166],
        [ 1.0136,  0.7271, -0.3054]])

# 1. intro to tensors

## scalar

In [5]:
# scalar
s = torch.tensor(7)

In [11]:
s.ndim

0

In [13]:
s.item()

7

## vector

In [22]:
vector = torch.tensor([323,35,32])
vector.shape

torch.Size([3])

In [18]:
vector.ndim

1

## matrix

In [23]:
MATRIX = torch.tensor([[123,123], [234,52]])

In [24]:
MATRIX.ndim

2

In [27]:
MATRIX.shape

torch.Size([2, 2])

## tensor

In [37]:
TENSOR = torch.tensor([[[23],[234]], [[234], [234]], [[123], [12]]])

In [38]:
TENSOR.shape

torch.Size([3, 2, 1])

In [39]:
TENSOR

tensor([[[ 23],
         [234]],

        [[234],
         [234]],

        [[123],
         [ 12]]])

In [40]:
TENSOR.ndim

3

## random tensors

In [56]:
t = torch.rand(2,2,5)

In [57]:
t.shape

torch.Size([2, 2, 5])

In [58]:
t

tensor([[[0.6730, 0.4839, 0.6900, 0.4395, 0.0807],
         [0.5760, 0.6465, 0.2345, 0.9310, 0.0818]],

        [[0.4155, 0.3865, 0.1001, 0.2843, 0.8917],
         [0.0118, 0.0833, 0.4436, 0.6692, 0.6194]]])

In [61]:
torch.rand((224, 224, 3)) # height width color channels

tensor([[[0.4189, 0.7582, 0.2998],
         [0.0833, 0.4676, 0.6756],
         [0.7476, 0.7512, 0.3844],
         ...,
         [0.1445, 0.0412, 0.3104],
         [0.6428, 0.7970, 0.0414],
         [0.5411, 0.6796, 0.8057]],

        [[0.1147, 0.9645, 0.6640],
         [0.7302, 0.1708, 0.7103],
         [0.5613, 0.9890, 0.5963],
         ...,
         [0.6036, 0.8062, 0.3942],
         [0.9443, 0.6764, 0.0183],
         [0.2947, 0.2903, 0.5000]],

        [[0.1606, 0.0326, 0.2943],
         [0.6269, 0.6406, 0.1108],
         [0.1792, 0.4023, 0.6704],
         ...,
         [0.8301, 0.1155, 0.6995],
         [0.2889, 0.8716, 0.8133],
         [0.4118, 0.9705, 0.4917]],

        ...,

        [[0.0154, 0.3355, 0.9964],
         [0.4754, 0.0851, 0.1450],
         [0.6736, 0.7307, 0.7418],
         ...,
         [0.9670, 0.7641, 0.4579],
         [0.8888, 0.9762, 0.8163],
         [0.9374, 0.7403, 0.4002]],

        [[0.7180, 0.4172, 0.9625],
         [0.1683, 0.2015, 0.4184],
         [0.

In [62]:
torch.rand(3,224, 224)

tensor([[[0.8594, 0.1381, 0.9999,  ..., 0.8225, 0.8154, 0.3657],
         [0.0594, 0.8029, 0.5839,  ..., 0.8131, 0.9306, 0.4708],
         [0.2104, 0.5523, 0.8750,  ..., 0.8540, 0.2225, 0.9920],
         ...,
         [0.9854, 0.4468, 0.7886,  ..., 0.1429, 0.9368, 0.8504],
         [0.0266, 0.0222, 0.4284,  ..., 0.1068, 0.0668, 0.6105],
         [0.1131, 0.6958, 0.6914,  ..., 0.3157, 0.7539, 0.9221]],

        [[0.0461, 0.6523, 0.5239,  ..., 0.9106, 0.3076, 0.9563],
         [0.1217, 0.3579, 0.7183,  ..., 0.6394, 0.6749, 0.3449],
         [0.4245, 0.6594, 0.1862,  ..., 0.2635, 0.1310, 0.3835],
         ...,
         [0.6691, 0.2055, 0.9638,  ..., 0.4555, 0.7838, 0.5418],
         [0.1553, 0.8011, 0.0199,  ..., 0.5881, 0.6933, 0.6824],
         [0.9486, 0.3689, 0.6044,  ..., 0.7793, 0.7797, 0.8674]],

        [[0.5035, 0.7741, 0.8072,  ..., 0.8212, 0.8467, 0.8979],
         [0.0579, 0.1798, 0.5593,  ..., 0.6066, 0.7026, 0.8134],
         [0.4883, 0.0940, 0.0975,  ..., 0.9196, 0.0364, 0.

In [64]:
torch.rand(size=(3,3))

tensor([[0.6423, 0.7158, 0.4485],
        [0.3601, 0.3093, 0.5995],
        [0.9186, 0.4600, 0.8813]])

## ZEROS AND ONES TENSORS

In [66]:
zero = torch.zeros(size= (3,3))

In [70]:
ones = torch.ones(size= (3,3,3))

In [71]:
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [72]:
ones*zero

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [75]:
torch.ones(size = (3,3), dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [81]:
torch.zeros(3,3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

## creating a range

In [125]:
a = torch.arange(1,11)

In [126]:
a = a.view(5,2)

In [127]:
matrix = torch.zeros_like(a)

In [128]:
matrix

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [129]:
torch.ones_like(a)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

# tensors data types

In [130]:
float32 = torch.tensor([32, 432.3], device='cpu')
float32.dtype

torch.float32

In [131]:
intensor = float32.type(dtype=torch.int32)

In [132]:
intensor

tensor([ 32, 432], dtype=torch.int32)

In [133]:
result = intensor * float32

In [134]:
result.dtype

torch.float32

In [135]:
float16 = float32.type(dtype=torch.float16)

In [136]:
(float16 * float32).dtype

torch.float32

In [137]:
torch.rand(3,3, dtype=torch.float64)

tensor([[0.9670, 0.0739, 0.9488],
        [0.2249, 0.3745, 0.6597],
        [0.1595, 0.2762, 0.6539]], dtype=torch.float64)

## tensor ops

In [145]:
a = torch.randn(2,3, dtype=torch.float32)

In [146]:
a

tensor([[-0.7273,  0.3692,  0.3042],
        [ 1.3753,  0.2102,  1.0640]])

In [148]:
b = torch.tensor(10)

In [149]:
a+b

tensor([[ 9.2727, 10.3692, 10.3042],
        [11.3753, 10.2102, 11.0640]])

In [150]:
a -10

tensor([[-10.7273,  -9.6308,  -9.6958],
        [ -8.6247,  -9.7898,  -8.9360]])

In [151]:
torch.mul(a, b)

tensor([[-7.2735,  3.6921,  3.0420],
        [13.7532,  2.1019, 10.6402]])

In [154]:
a.shape

torch.Size([2, 3])

In [164]:
a.matmul(torch.rand(3,))

# matmul is same as dot product

tensor([-0.3369,  1.1823])

In [165]:
torch.mul(a, torch.rand(3,))


tensor([[-0.4801,  0.1613,  0.1165],
        [ 0.9079,  0.0918,  0.4076]])

In [ ]:

a @ torch.rand(size = (3,))

tensor([-0.1572,  1.5958])

In [223]:
%%time
a = torch.rand(103,103)

value = 0

for i in range(len(a)):
    for j in range(len(a)):
        value += a[i][j]

print(value)

tensor(5319.8867)
CPU times: user 27.6 ms, sys: 1.06 ms, total: 28.6 ms
Wall time: 27.9 ms


In [224]:
%%time
value =0
a = torch.rand(103,103)
value += torch.matmul(a, a)
print(value)

tensor([[23.6441, 23.1711, 23.8877,  ..., 23.8904, 22.8909, 24.6980],
        [28.8421, 26.2622, 29.2790,  ..., 26.9196, 25.7185, 28.2070],
        [26.9711, 25.2760, 27.3282,  ..., 25.3438, 24.8026, 26.1572],
        ...,
        [28.0309, 24.8304, 26.1176,  ..., 25.9816, 24.7814, 25.9657],
        [26.1765, 23.7838, 27.5251,  ..., 24.5048, 21.9022, 26.5273],
        [24.7357, 23.2056, 26.2543,  ..., 24.5434, 23.6922, 25.0255]])
CPU times: user 1.26 ms, sys: 920 μs, total: 2.18 ms
Wall time: 1.25 ms


In [225]:
tensor_a = torch.arange(1,82)

In [226]:
tensor_a = tensor_a.view(9,9)

In [227]:
tensor_a

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60, 61, 62, 63],
        [64, 65, 66, 67, 68, 69, 70, 71, 72],
        [73, 74, 75, 76, 77, 78, 79, 80, 81]])

In [228]:
tensor_b = tensor_a +10

In [230]:
tensor_a + tensor_b

tensor([[ 12,  14,  16,  18,  20,  22,  24,  26,  28],
        [ 30,  32,  34,  36,  38,  40,  42,  44,  46],
        [ 48,  50,  52,  54,  56,  58,  60,  62,  64],
        [ 66,  68,  70,  72,  74,  76,  78,  80,  82],
        [ 84,  86,  88,  90,  92,  94,  96,  98, 100],
        [102, 104, 106, 108, 110, 112, 114, 116, 118],
        [120, 122, 124, 126, 128, 130, 132, 134, 136],
        [138, 140, 142, 144, 146, 148, 150, 152, 154],
        [156, 158, 160, 162, 164, 166, 168, 170, 172]])

In [246]:
tensor_h = torch.arange(27)

In [247]:
tensor_k = tensor_h.view(9, 3)

In [249]:
tensor_k.shape

torch.Size([9, 3])

In [250]:
tensor_h.shape

torch.Size([27])

In [252]:
tensor_h.view(3,9) @ tensor_k

tensor([[ 612,  648,  684],
        [1584, 1701, 1818],
        [2556, 2754, 2952]])

In [253]:
tensor_h

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])

In [255]:
tensor_k @ tensor_h.view(3, -1)

tensor([[  45,   48,   51,   54,   57,   60,   63,   66,   69],
        [ 126,  138,  150,  162,  174,  186,  198,  210,  222],
        [ 207,  228,  249,  270,  291,  312,  333,  354,  375],
        [ 288,  318,  348,  378,  408,  438,  468,  498,  528],
        [ 369,  408,  447,  486,  525,  564,  603,  642,  681],
        [ 450,  498,  546,  594,  642,  690,  738,  786,  834],
        [ 531,  588,  645,  702,  759,  816,  873,  930,  987],
        [ 612,  678,  744,  810,  876,  942, 1008, 1074, 1140],
        [ 693,  768,  843,  918,  993, 1068, 1143, 1218, 1293]])