In [2]:
import torch

In [3]:
a = torch.arange(1, 101)

In [4]:
a.dtype

torch.int64

In [5]:
torch.max(a)

tensor(100)

In [10]:
a = a.type(dtype=torch.float64)

torch.mean(a)

tensor(50.5000, dtype=torch.float64)

In [11]:
a.mean()

tensor(50.5000, dtype=torch.float64)

In [12]:
a.sum()/len(a)

tensor(50.5000, dtype=torch.float64)

In [16]:
a.argmin() # for index

tensor(0)

In [15]:
a.min()

tensor(1., dtype=torch.float64)

## reshape

In [40]:
a = torch.arange(1, 101)

In [41]:
a.shape

torch.Size([100])

In [42]:
a = a.reshape(25,4)

In [43]:
a.dtype

torch.int64

In [44]:
b = a.view(100)

In [45]:
b

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100])

In [46]:
a

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40],
        [ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60],
        [ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80],
        [ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]])

In [47]:
a+=100

In [48]:
a

tensor([[101, 102, 103, 104],
        [105, 106, 107, 108],
        [109, 110, 111, 112],
        [113, 114, 115, 116],
        [117, 118, 119, 120],
        [121, 122, 123, 124],
        [125, 126, 127, 128],
        [129, 130, 131, 132],
        [133, 134, 135, 136],
        [137, 138, 139, 140],
        [141, 142, 143, 144],
        [145, 146, 147, 148],
        [149, 150, 151, 152],
        [153, 154, 155, 156],
        [157, 158, 159, 160],
        [161, 162, 163, 164],
        [165, 166, 167, 168],
        [169, 170, 171, 172],
        [173, 174, 175, 176],
        [177, 178, 179, 180],
        [181, 182, 183, 184],
        [185, 186, 187, 188],
        [189, 190, 191, 192],
        [193, 194, 195, 196],
        [197, 198, 199, 200]])

In [49]:
 b

tensor([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184,
        185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198,
        199, 200])

# stacking

In [50]:
c = b

In [51]:
c

tensor([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184,
        185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198,
        199, 200])

In [52]:
c += 100

In [53]:
c

tensor([201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
        215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
        229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
        243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
        257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
        271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284,
        285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
        299, 300])

In [54]:
d = c+100

In [55]:
d

tensor([301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314,
        315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328,
        329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
        343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356,
        357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370,
        371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384,
        385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398,
        399, 400])

In [56]:
c

tensor([201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
        215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
        229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
        243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
        257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
        271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284,
        285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
        299, 300])

In [57]:
a

tensor([[201, 202, 203, 204],
        [205, 206, 207, 208],
        [209, 210, 211, 212],
        [213, 214, 215, 216],
        [217, 218, 219, 220],
        [221, 222, 223, 224],
        [225, 226, 227, 228],
        [229, 230, 231, 232],
        [233, 234, 235, 236],
        [237, 238, 239, 240],
        [241, 242, 243, 244],
        [245, 246, 247, 248],
        [249, 250, 251, 252],
        [253, 254, 255, 256],
        [257, 258, 259, 260],
        [261, 262, 263, 264],
        [265, 266, 267, 268],
        [269, 270, 271, 272],
        [273, 274, 275, 276],
        [277, 278, 279, 280],
        [281, 282, 283, 284],
        [285, 286, 287, 288],
        [289, 290, 291, 292],
        [293, 294, 295, 296],
        [297, 298, 299, 300]])

In [58]:
b

tensor([201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
        215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
        229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
        243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
        257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
        271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284,
        285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
        299, 300])

In [102]:
a = torch.arange(1,7,)
a.shape
v_stacked = torch.stack([a,a]).squeeze()
v_stacked, v_stacked.shape

(tensor([[1, 2, 3, 4, 5, 6],
         [1, 2, 3, 4, 5, 6]]),
 torch.Size([2, 6]))

In [107]:
h_stacked = torch.stack([a,a], dim=1)

h_stacked, h_stacked.shape

(tensor([[1, 1],
         [2, 2],
         [3, 3],
         [4, 4],
         [5, 5],
         [6, 6]]),
 torch.Size([6, 2]))

In [104]:
c = torch.hstack([a,a])

In [105]:
c.shape

torch.Size([12])

In [106]:
a 

tensor([1, 2, 3, 4, 5, 6])

In [83]:
d = torch.vstack([a,a])

In [85]:
d, d.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6]]),
 torch.Size([12, 1]))

In [101]:
a = a.view(1,6)
e = torch.stack([a,a], dim=0)
e.shape

torch.Size([2, 1, 6])

In [89]:
e = torch.stack([a,a], dim=1)

In [91]:
e, e.shape

(tensor([[[1],
          [1]],
 
         [[2],
          [2]],
 
         [[3],
          [3]],
 
         [[4],
          [4]],
 
         [[5],
          [5]],
 
         [[6],
          [6]]]),
 torch.Size([6, 2, 1]))

In [108]:
a = torch.arange(1,7)

In [109]:
a

tensor([1, 2, 3, 4, 5, 6])

In [110]:
hs = torch.hstack([a,a])

In [111]:
hs.shape

torch.Size([12])

## torch.permute

In [125]:
mat = torch.arange(1,19).view(3,2,3)

In [126]:
mat

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [127]:
mat.shape

torch.Size([3, 2, 3])

In [129]:
permuted = mat.permute(1,0,2)

In [130]:
permuted

tensor([[[ 1,  2,  3],
         [ 7,  8,  9],
         [13, 14, 15]],

        [[ 4,  5,  6],
         [10, 11, 12],
         [16, 17, 18]]])

In [131]:
mat.view(2,3,3)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [132]:
mat[0,0,0] = 100

In [133]:
mat

tensor([[[100,   2,   3],
         [  4,   5,   6]],

        [[  7,   8,   9],
         [ 10,  11,  12]],

        [[ 13,  14,  15],
         [ 16,  17,  18]]])

In [134]:
permuted

tensor([[[100,   2,   3],
         [  7,   8,   9],
         [ 13,  14,  15]],

        [[  4,   5,   6],
         [ 10,  11,  12],
         [ 16,  17,  18]]])

## 1. indexing with pytorch

In [135]:
x = torch.arange(1, 10).reshape(1,3,3)

In [136]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [137]:
x.shape

torch.Size([1, 3, 3])

In [138]:
x[0, :, 0]

tensor([1, 4, 7])

In [139]:
x[0,0]

tensor([1, 2, 3])

In [142]:
x[0,1,2]

tensor(6)

In [157]:
x[0,2].tolist()[::-1]

[9, 8, 7]

In [158]:
import numpy as np

In [159]:
ar = np.arange(1,8)

In [162]:
t = torch.from_numpy(ar)


In [163]:
t

tensor([1, 2, 3, 4, 5, 6, 7])

In [164]:
ar+=1

In [165]:
ar

array([2, 3, 4, 5, 6, 7, 8])

In [166]:
t

tensor([2, 3, 4, 5, 6, 7, 8])

In [167]:
ar = ar+1

In [168]:
t

tensor([2, 3, 4, 5, 6, 7, 8])

In [169]:
ar

array([3, 4, 5, 6, 7, 8, 9])

## random

In [175]:
torch.manual_seed(32)
a = torch.randn(3,3)
torch.manual_seed(32)
b = torch.randn(3,3)

print(a==b)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [177]:
torch.cuda.is_available()

False

In [193]:
mata = torch.randn(10000,10000, device='mps')

In [194]:
torch.mps.is_available()

True

In [199]:
%%time
mata @ mata

CPU times: user 796 μs, sys: 754 μs, total: 1.55 ms
Wall time: 616 μs


tensor([[  19.7572,  -88.9070,   95.6499,  ...,  -13.3618,  -60.7365,
           54.8082],
        [  51.5427,  -62.2663, -142.9468,  ...,   41.8499,  279.3178,
          -22.5048],
        [ -25.4733,  188.4113,  -34.7179,  ...,  104.7252,   46.0876,
            4.7989],
        ...,
        [ -37.6400,    3.7744, -145.8085,  ...,   20.4580, -157.8454,
         -127.4888],
        [ -61.6540,  114.1028,  -18.2119,  ...,  105.3985,   75.9067,
          159.2108],
        [-151.0673,   14.1560,   81.7094,  ...,   57.4661,   68.7680,
           94.4613]], device='mps:0')

In [200]:
a = torch.randn(10000,10000)


In [201]:
%%time
a @a

CPU times: user 2.14 s, sys: 14 ms, total: 2.15 s
Wall time: 1.12 s


tensor([[-222.5011,  168.2323,  -56.3626,  ...,   69.2436,   -8.1456,
          210.0698],
        [ 140.5655,  197.8852,  -33.0670,  ..., -208.8908,   53.8721,
           22.2076],
        [-160.5533,   -1.6883,    7.8962,  ...,  138.9537, -102.2533,
          -11.4855],
        ...,
        [  41.2562,  -28.2539,  107.0019,  ..., -163.0302, -139.2244,
           59.3585],
        [-127.8492,  -37.9136,   63.5427,  ..., -112.0295,   -6.3551,
          102.7272],
        [-154.5818, -212.4241,   21.2529,  ..., -176.9205,  -24.5151,
           80.0576]])